name: WakaTime Stats Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Updates daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_REPO }}
